### ISSUE TITLE
Question: automatically fill in calibration for auxiliary variables?

### ISSUE THREAD

**Issue by spencerlyon2** [EconForge/dolo#85] opened 2016-02-27 16:29 UTC
Auxiliary variables are defined as pure functions of the state and control. If those two sets of variable are fully specified in a calibration, do we want to fill in the implied auxiliary variables for the user?

**Comment by albop** [comment] 2016-03-01 18:24
This is a good remark.

Most of the time, it should not be an actual nuisancce though, as most algorithm should not use the calibrated values for auxiliaries at all (since they will also be functions of states and controls only). In particular, you should be able to leave them blank and not notice anything wrong if you run the usual algorithms. But the `model.calibration['auxiliaries']`  field will contain which can be a problem if you try to access steady state values.

So much for the "this is not a bug, it's a feature"  answer. Now the real one:

1. the bug also occurs for all variables which are defined by a "defiinition block"  where left-hand side is defined as a function of right hand-side (values, expectations, auxiliaries)
2. there are at least two ways to fix it:
   1. once model.calibration is defined in the initialization of the `ModelNumeric` object, fill `model.calibration['auxiliaries']`  with the adequate values
   2. when creating the `model.symbolic` object (which represents everything as symbolic strings), fill in auxiliary variables in the calibration dictionary with the equations from models after replacing all variables by their steady-state values

Options 2.1 is very easy to implement. It introduces a slight disconnection between the symbolic and numeric objects. To save time, it could also be done without jitting the model functions by calling the python version instead.
Option 2.2 just requires to operate some transformations on the model equations.

I think I have a slight preference for option 2.2 but I am not 100% sure.

Actually, the more I think about it, the more I dislike the concept of these auxiliary variables. It induces the creation of a whole hidden hierarchy of models (the `dtcscc_` are the `dtcscc` models with auxiliary variables).
I wonder if they couldn't be merged with the currently undocumented definitions block. This would allow for any timing in "auxiliary" definitions.

This is related to issue https://github.com/EconForge/dolo/issues/84

**Comment by spencerlyon2** [comment] 2016-03-07 12:54
If we had to pick between one of the options up there I'd also vote for 2.2. When I fill in the calibration for auxiliary variables this is exactly what I do (copy/paste from the equations section and delete any notion of timing).

I think it'd be great to somehow allow arbitrary timing in these variables. You're right that solution algorithms don't use the auxiliary definitions. I mostly want them around for two reasons:

1. Make the model definition self contained in the yaml file 
2.  Get the auxiliary variables in a simulation of the model. 

If we could make this happen with "looser" definition of auxiliary variable (i.e. by merging them with the definitions block and support arbitrary timing) that would be fantastic.

**Closed** 2016-03-22 13:33 UTC
